service: 
  auction-project

plugins:
  - serverless-bundle

variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  lambdaHashingVersion: 20201221
  environment:
    AUCTION_TABLE_NAME: ${self:custom.AuctionTable.name}
    MAIL_QUEUE_URL: ${self:custom.mailQueue.url}
    AUCTION_BUCKET_NAME: ${self:custom.AuctionsBucket.name}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  iamRoleStatements:
    - ${file(iam/auctionTableIAM.yaml):AuctionTableIAM}
    - ${file(iam/mailQueueIAM.yml):SQSQueueIAM}
    - ${file(iam/AuctionsBucketIAM.yml):AuctionsBucketIAM}

resources:
  Resources:
    AuctionTable: ${file(resources/auctionTable.yaml):AuctionTable}
    AuctionsBucket: ${file(resources/auctionsBucket.yml):AuctionsBucket}
    AuctionsBucketPolicy: ${file(resources/auctionsBucket.yml):AuctionsBucketPolicy}
    
functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction  
          cors: true
          authorizer: ${self:custom.authorizer}

  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - http:
          method: GET
          path: /auctions
          cors: true
          authorizer: ${self:custom.authorizer}
  getAuction:
    handler: src/handlers/getAuction.handler
    events:
      - http:
          method: GET
          path: /auction/{id}
          cors: true
          authorizer: ${self:custom.authorizer}
  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - http:
          method: PATCH
          path: auction/{id}/bid
          cors: true
          authorizer: ${self:custom.authorizer}
  uploadAuctionsPicture:
    handler: src/handlers/uploadAuctionsPicture.handler
    events:
      - http:
          method: PATCH
          path: auction/{id}/uploadAuctionsPicture
          cors: true
          authorizer: ${self:custom.authorizer}
  processAuctions:
    handler: src/handlers/processAuctions.handler
    # events:
    #   - schedule: rate(10 minutes)

custom:
  authorizer: arn:aws:lambda:${aws:region}:${aws:accountId}:function:auth-service-${self:provider.stage}-auth
  AuctionTable:
    name: !Ref AuctionTable
    arn: !GetAtt AuctionTable.Arn
  mailQueue:
    arn: ${cf:notification-service-${self:provider.stage}.MailQueueArn}
    url: ${cf:notification-service-${self:provider.stage}.MailQueueUrl}
  AuctionsBucket:
    name: auction-project-sdfacklwl212d-${self:provider.stage}